### ISSUE TITLE
No definition found for class:'io.refiner.ui.RefinerSurveyViewModel'

### ISSUE THREAD

**Issue by jeremiahk** [refiner-io/mobile-sdk-android#1]
We are seeing a crash when calling `Refiner.trackScreen()`. It is happening across all devices and Android versions. 

```
Caused by org.koin.core.error.NoBeanDefFoundException: No definition found for class:'io.refiner.ui.RefinerSurveyViewModel' q:''. Check your definitions!
       at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:298)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:268)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
       at org.koin.core.scope.Scope.get(Scope.kt:210)
       at io.refiner.Refiner$o.invoke(SourceFile:3)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at io.refiner.Refiner.getViewModel(SourceFile:1)
       at io.refiner.Refiner.trackScreen(SourceFile:1)
       at com.directfreight.driver.analytics.RefinerFragment.onStart(Refiner.kt:51)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3162)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:588)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by chezmo** [comment]
Hi @jeremiahk ! I'm sorry to hear that you are experiencing those crashes. We are looking into this and I'll get back to you one we tracked down the issue.
