### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jeff-emuveyan2024** [refiner-io/mobile-sdk-android#14]
Hi @tekinalper 

We are having two crash reports related to Refiner android sdk. These are the crash logs:

1)
 Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property koinApp has not been initialized
       at io.refiner.shared.LibKoinContext.getKoinApp(Koin.kt:27)
       at io.refiner.w0.invoke(SourceFile:1)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at io.refiner.ui.RefinerSurveyFragment.getViewModel(SourceFile:1)
       at io.refiner.ui.RefinerSurveyFragment.onCreate(SourceFile:11)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:3099)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:524)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2065)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3267)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3177)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
       at android.app.Activity.performStart(Activity.java:9008)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4198)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

2)
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.motain.iliga/io.refiner.ui.RefinerSurveyActivity}: kotlin.UninitializedPropertyAccessException: lateinit property koinApp has not been initialized
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3839)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3985)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2420)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8227)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by tekinalper** [comment]
Hi @jeff-emuveyan2024,

- Which version are the crash reports related with? 
- Just to double check; you're calling initialize method in your application class before calling any Refiner SDK method, right?

**Comment by jeff-emuveyan2024** [comment]
1) the version is 1.5.0
2) Yes, we initialise the sdk firat before calling any other method.
